import Head from "next/head";
import { useEffect } from "react";
import { useState } from "react";
import PostList from "src/components/Post/PostList";
import { client } from "src/utils/client";

export default function Home() {
  const [posts, setPosts] = useState([]);

  const useFetchPosts = async () => {
    const data = await client.get({ endpoint: "posts" });
    setPosts(data.contents);
  };

  useEffect(() => {
    useFetchPosts();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostList posts={posts} />
    </div>
  );
}
