import Head from "next/head";

function custom() {
  return (
    <div>
      <Head>
        <title>404</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>404</h1>
      </main>
    </div>
  );
}

export default custom;