import Head from "next/head";
import useSWR from "swr";

export default function Home() {
  const { data, error } = useSWR("https://jsonplaceholder.typicode.com/users");

  console.log({ data, error });

  if (!data && !error) {
    return <div>Loading...</div>;
  }

  if (error) return <div>failed to load</div>;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{data[0].name}</h1>
        <p>{data[0].email}</p>
      </main>
    </div>
  );
}
