import Head from "next/head";
import { client } from "src/utils/client";
import { useEffect } from "react";
import { useState } from "react";
import Link from "next/link";

export default function Home() {
  const [posts, setPosts] = useState([]);

  const getData = async () => {
    const data = await client.get({ endpoint: "posts" });
    setPosts(data.contents);
  };

  useEffect(() => {
    getData();
  }, []);

  console.log(posts);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {posts.map((post) => {
          return (
            <li key={post.id}>
              <Link href={post.id}>
                <a>{post.title}</a>
              </Link>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
